version: "3.8"

services:
  erlbrew-cafe:
    build: .
    container_name: erlbrew-cafe
    restart: unless-stopped
    ports:
      - "3003:80"
    networks:
      - web

networks:
  web:
    external: false